swagger: "2.0"
info:
  contact: {}
  version: "1.0"
  title: "intern-assignment"
host: "localhost:3000"
basePath: "/"
paths: 
  /members: 
    get: 
      produces: 
      - "application/json"
      tags: 
      - "Members"
      summary: "Index"
      responses: 
        200: 
          description: "OK"
          schema: 
            type: "array"
            items: 
              $ref: "#/definitions/Member"
        400: 
          description: "Bad Request"
          schema: 
            $ref: "#/definitions/Error"
    post: 
      produces: 
      - "application/json"
      tags: 
      - "Member"
      summary: "Create"
      parameters: 
      - type: "string"
        description: "Employee Number"
        name: "no"
        in: "query"
      - type: "string"
        description: "Full Name"
        name: "full_name"
        in: "query"
      - type: "string"
        description: "Profile Image"
        name: "profile_img"
        in: "query"
      - type: "string"
        description: "Kana Name"
        name: "kana_name"
        in: "query"
      - type: "string"
        description: "Employment Start Date"
        name: "start_date"
        in: "query"
      - type: "string"
        description: "Emoployment End Date"
        name: "end_date"
        in: "query"
      - type: "integer"
        description: "Employment Status"
        name: "employment_status_id"
        in: "query"
        required: true
      - type: "integer"
        description: "Status"
        name: "status_id"
        in: "query"
      responses: 
        201: 
          description: "Created"
          schema: 
            $ref: "#/definitions/Member"
        400: 
          description: "Bad Request"
          schema: 
            $ref: "#/definitions/Error"
  /members/{id}: 
    get: 
      produces: 
      - "application/json"
      tags: 
      - "Member"
      summary: "Show"
      parameters: 
      - type: string
        description: "ID"
        name: "id"
        in: "path"
        required: true
      responses: 
        200: 
          description: "OK"
          schema: 
            $ref: "#/definitions/Member"
        400: 
          description: "Bad Request"
          schema: 
            $ref: "#/definitions/Error"
    put: 
      produces: 
      - "application/json"
      tags: 
      - "Member"
      summary: "Update"
      parameters: 
      - type: string
        description: "ID"
        name: "id"
        in: "path"
        required: true
      - type: string
        description: "Employee Number"
        name: "no"
        in: "query"
        required: true
      - type: string
        description: "Full Name"
        name: "full_name"
        in: "query"
      - type: string
        description: "Profile Image"
        name: "profile_img"
        in: "query"
        required: true
      - type: string
        description: "Kana Name"
        name: "kana_name"
        in: "query"
      - type: string
        description: "Employment Start Date"
        name: "start_date"
        in: "query"
        required: true
      - type: string
        description: "Emoployment End Date"
        name: "end_date"
        in: "query"
        required: true
      - type: integer
        description: "Employment Status"
        name: "employment_status_id"
        in: "query"
      - type: integer
        description: "Status"
        name: "status_id"
        in: query
      responses: 
        201: 
          description: "Created"
          schema: 
            $ref: "#/definitions/Member"
        400: 
          description: "Bad Request"
          schema: 
            $ref: "#/definitions/Error"
    delete: 
      produces: 
      - "application/json"
      tags: 
      - "Member"
      summary: "Delete"
      parameters: 
      - type: string
        description: "ID"
        name: "id"
        in: "path"
        required: true
      responses: 
        200: 
          description: "OK"
          schema: 
            $ref: "#/definitions/Member"
        400: 
          description: "Bad Request"
          schema: 
            $ref: "#/definitions/Error"
definitions: 
  Error: 
    type: "object"
    properties: 
      message: 
        type: "string"
      status: 
        type: "integer"
  Member: 
    type: "object"
    properties: 
      id: 
        type: "integer"
      no: 
        type: "string"
      profile_img: 
        type: "string"
      full_name: 
        type: "string"
      kana_name: 
        type: "string"
      motto: 
        type: "string"
      biography: 
        type: "string"
      start_date: 
        type: "string"
      end_date: 
        type: "string"
      employment_status: 
        type: "integer"
      status: 
        type: "integer"